<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>5b51036a-a54d-4e08-b803-ab7a5852d9ac</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Approved" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
