<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>second</name>
  <uuid>0dc6213e-c5bb-4476-a457-75215a1262e3</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Decision is at least 0 and less than 40
then
	set decision to "Rejected" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
