<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>first</name>
  <uuid>512e39b5-d0bf-4d6a-94b7-6f167f8b404c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
	Input is "abc"
then
	set decision to 50 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
