<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>02cfe68a-b59e-4f2a-99bd-ce73bb5b32cb</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 25 ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
